# Change these first
owner: globalmsq # Your GitHub organization or username, where this repository lives
repo: mufin-uptime # The name of this repository

sites:
  - name: Dev Businesshub
    url: https://dev.businesshub.co.kr/
  - name: Staging Businesshub
    url: https://stg.businesshub.co.kr/
  - name: Production Businesshub
    url: https://businesshub.co.kr/
  - name: Test Page
    url: https://tst.businesshub.co.kr/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: newstatus.mufin.lol
  # baseUrl: /your-repo-name
  logoUrl: https://www.mufin.co.kr/images/logo.svg
  name: Upptime
  introTitle: "**Must Fintech**"
  introMessage: "Status Page"
  navbar:
    - title: Homepage
      href: https://www.mufin.co.kr
    - title: Status
      href: /
    - title: Github
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
