# Change these first
owner: globalmsq # Your GitHub organization or username, where this repository lives
repo: mufin-uptime # The name of this repository

sites:
## Businesshub
  - name: Businesshub Dev
    url: https://dev.businesshub.co.kr/
  - name: Businesshub Stg
    url: https://stg.businesshub.co.kr/
  - name: Businesshub Prd
    url: https://businesshub.co.kr/
  - name: Businesshub ERP Dev
    url: https://dev-erp.businesshub.co.kr/
  - name: Businesshub ERP Stg
    url: https://stg-erp.businesshub.co.kr/
  - name: Businesshub ERP Prd
    url: https://erp.businesshub.co.kr/
##54DNA
  - name: 54DNA Dev
    url: https://dev.54dnatype.com/
  - name: 54DNA Prd
    url: https://www.54dnatype.com/
  - name: 54DNA API Dev
    url: dev-api.54dnatype.com
    check: "tcp-ping"
    port: 443
  - name: 54DNA API Prd
    url: api.54dnatype.com
    check: "tcp-ping"
    port: 443
## Mufin translator
  - name: Mufin Translator Dev
    url: https://dev-translator.mufin.lol/
  - name: Mufin Translator Stg
    url: https://stg-translator.mufin.lol/
  - name: Mufin Translator Prd
    url: https://translator.mufin.lol/
  - name: Mufin Translator API Dev
    url: https://dev-api-translator.mufin.lol/
  - name: Mufin Translator API Stg
    url: https://stg-api-translator.mufin.lol/
  - name: Mufin Translator API Prd
    url: https://prd-api-translator.mufin.lol/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: newstatus.mufin.lol
  # baseUrl: /your-repo-name
  logoUrl: https://www.mufin.co.kr/images/logo.svg
  name: Upptime
  introTitle: "**Must Fintech**"
  introMessage: "Status Page"
  navbar:
    - title: Homepage
      href: https://www.mufin.co.kr
    - title: Status
      href: /
    - title: Github
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
